2023 Drive base: frc.robot.subsystems.Controller Class Reference
frc.robot.subsystems.Controller Class Reference
Public Member Functions
Controller ()
double getLeftX ()
double getLeftY ()
double getRightX ()
double getRightY ()
Private Member Functions
double applyPreferences (double input, double exponent)
Detailed Description
Definition at line 6 of file Controller.java.
Constructor & Destructor Documentation
Controller()
frc.robot.subsystems.Controller.Controller ()
Definition at line 8 of file Controller.java.
{
        super(Constants.XBOX_CONTROLLER_PORT);
    }
References frc.robot.Constants.XBOX_CONTROLLER_PORT.
Member Function Documentation
applyPreferences()
double frc.robot.subsystems.Controller.applyPreferences (double input, double exponent) private
Definition at line 13 of file Controller.java.
{
        if (Math.abs(input) < Constants.ANALOG_DEAD_ZONE) {
            input = 0;
        }
        input = Math.pow(Math.abs(input), exponent) * Math.signum(input);
        return input;
    }
References frc.robot.Constants.ANALOG_DEAD_ZONE.
Referenced by frc.robot.subsystems.Controller.getLeftX(), frc.robot.subsystems.Controller.getLeftY(), frc.robot.subsystems.Controller.getRightX(), and frc.robot.subsystems.Controller.getRightY().
getLeftX()
double frc.robot.subsystems.Controller.getLeftX ()
Definition at line 23 of file Controller.java.
{
        return applyPreferences(super.getLeftX(), Constants.LEFT_X_EXPONENT);
    }
References frc.robot.subsystems.Controller.applyPreferences(), and frc.robot.Constants.LEFT_X_EXPONENT.
Referenced by frc.robot.Robot.drive().
getLeftY()
double frc.robot.subsystems.Controller.getLeftY ()
Definition at line 29 of file Controller.java.
{
        return applyPreferences(-super.getLeftY(), Constants.LEFT_Y_EXPONENT);
    }
References frc.robot.subsystems.Controller.applyPreferences(), and frc.robot.Constants.LEFT_Y_EXPONENT.
Referenced by frc.robot.Robot.drive().
getRightX()
double frc.robot.subsystems.Controller.getRightX ()
Definition at line 34 of file Controller.java.
{
        return applyPreferences(super.getRightX(), Constants.RIGHT_X_EXPONENT);
    }
References frc.robot.subsystems.Controller.applyPreferences(), and frc.robot.Constants.RIGHT_X_EXPONENT.
Referenced by frc.robot.Robot.drive().
getRightY()
double frc.robot.subsystems.Controller.getRightY ()
Definition at line 40 of file Controller.java.
{
        return applyPreferences(-super.getRightY(), Constants.RIGHT_Y_EXPONENT);
    }
References frc.robot.subsystems.Controller.applyPreferences(), and frc.robot.Constants.RIGHT_Y_EXPONENT.
The documentation for this class was generated from the following file:
Controller.java