2023 Drive base: frc.robot.subsystems.MecaDrive Class Reference
frc.robot.subsystems.MecaDrive Class Reference
Public Member Functions
MecaDrive (int frontLeftMotorPort, int frontRightMotorPort, int rearLeftMotorPort, int rearRightMotorPort, IMU imu)
void drive (double speedX, double speedY, double rotateSpeed)
void printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
void cycleMotor ()
Cycle between each motor during debug mode.
void printActiveMotorDebugMode ()
prints the number of the currently activated motors during debug mode
void periodic ()
void updateOdometry ()
Pose2d getPose ()
Returns the currently-estimated pose of the robot.
double getOdomX ()
double getOdomY ()
double getOdomHeading ()
void resetOdometry (Pose2d pose)
Resets the odometry to the specified pose.
Public Member Functions inherited from frc.robot.subsystems.DriveBase
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot with controller input.
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX)
abstract void printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
void increaseSpeedBracket ()
The speed bracket controls the multiplier for al the speeds So when you change it, lets say, to 1/2 speed, all movement will be at 1/2 speed.
void decreaseSpeedBracket ()
void turnOnDefaultMode ()
void turnOnDebugMode ()
void turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
void turnONPIDTuningMode ()
abstract void cycleMotor ()
Needs to be implemented in sub classes becuase there might be different numbers of motors.
void AButtonPressed ()
void BButtonPressed ()
void XButtonPressed ()
void YButtonPressed ()
void leftBumperPressed ()
void rightBumperPressed ()
Mode getCurrentMode ()
void setCurrentMode (Mode currentMode)
int getDebugEnabledMotor ()
void setDebugEnabledMotor (int debugEnabledMotor)
Trajectory getCurrentTrajectory ()
void setCurrentTrajectory (Trajectory currentTrajectory)
TrajectoryConfig getTrajectoryConfig ()
RamseteController getChassisController ()
double getCurrentTrajectoryTime ()
void setCurrentTrajectoryTime (double newTrajectoryTime)
Private Member Functions
double slowDown (double inputVelocity)
This will return a value lower than the input, and it is used to slow down the motors during stop mode.
double convertPosition (double rawPosition)
Converts raw position units to meters.
double convertVelocity (double rawVelocity)
Converts raw sensor velocity to meters/second.
Additional Inherited Members
Protected Attributes inherited from frc.robot.subsystems.DriveBase
TrajectoryConfig trajectoryConfig
Detailed Description
Definition at line 18 of file MecaDrive.java.
Constructor & Destructor Documentation
MecaDrive()
frc.robot.subsystems.MecaDrive.MecaDrive (int frontLeftMotorPort, int frontRightMotorPort, int rearLeftMotorPort, int rearRightMotorPort, IMU imu)
Definition at line 39 of file MecaDrive.java.
{
        frontLeftMotor = new WPI_TalonFX(frontLeftMotorPort);
        frontRightMotor = new WPI_TalonFX(frontRightMotorPort);
        rearLeftMotor = new WPI_TalonFX(rearLeftMotorPort);
        rearRightMotor = new WPI_TalonFX(rearRightMotorPort);
        // invert motors to make forward the right direction
        frontRightMotor.setInverted(true);
        rearRightMotor.setInverted(true);
        // zero encoders
        frontLeftMotor.setSelectedSensorPosition(0);
        frontRightMotor.setSelectedSensorPosition(0);
        rearLeftMotor.setSelectedSensorPosition(0);
        rearRightMotor.setSelectedSensorPosition(0);
        mDrive = new MecanumDrive(frontLeftMotor, rearLeftMotor, frontRightMotor, rearRightMotor);
        this.imu = imu;
        // Odometry: !!secondary constructor takes initialPose argument
        mOdom = new MecanumDriveOdometry(Constants.MECANUM_KINEMATICS, new Rotation2d(Math.toRadians(imu.getAngle())), getWheelPositions());
        // see declaration in DriveBase
        trajectoryConfig = new TrajectoryConfig(Constants.maxVelocityMetersPerSecond, Constants.maxAccelerationMetersPerSecond);
        trajectoryConfig.setReversed(true);
    }
References frc.robot.Constants.maxAccelerationMetersPerSecond, frc.robot.Constants.maxVelocityMetersPerSecond, frc.robot.Constants.MECANUM_KINEMATICS, and frc.robot.subsystems.DriveBase.trajectoryConfig.
Member Function Documentation
convertPosition()
double frc.robot.subsystems.MecaDrive.convertPosition (double rawPosition) private
Converts raw position units to meters.
Parameters
rawPosition the position from an encoder in raw sensor units
Returns
the position in meters
Definition at line 197 of file MecaDrive.java.
{
        // raw units are "clicks," so divide by "clicks" per rotation to get rotations
        // also account for gear ratio because the encoders measure motor output, not actual wheel
        double position = rawPosition / (Constants.TALON_FX_CPR * Constants.FALCON_GEARBOX_RATIO);
        // multiply by circumference to get linear distance
        position *= Math.PI * Constants.MECANUM_WHEEL_DIAMETER;
        return position;
    }
References frc.robot.Constants.FALCON_GEARBOX_RATIO, and frc.robot.Constants.MECANUM_WHEEL_DIAMETER.
convertVelocity()
double frc.robot.subsystems.MecaDrive.convertVelocity (double rawVelocity) private
Converts raw sensor velocity to meters/second.
Parameters
rawVelocity the velocity from an encoder in raw sensor units
Returns
velocity in m/s
Definition at line 226 of file MecaDrive.java.
{
        // convert to rotations per second because raw units are "clicks" per 100ms
        // also account for gear ratio because the encoders measure motor output, not actual wheel
        double velocity = rawVelocity / (Constants.TALON_FX_CPR * Constants.FALCON_GEARBOX_RATIO) * 10;
        // multiply by circumference to get linear velocity
        velocity *= Math.PI * Constants.MECANUM_WHEEL_DIAMETER;
        return velocity;
    }
References frc.robot.Constants.FALCON_GEARBOX_RATIO, and frc.robot.Constants.MECANUM_WHEEL_DIAMETER.
cycleMotor()
void frc.robot.subsystems.MecaDrive.cycleMotor ()
Cycle between each motor during debug mode.
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 164 of file MecaDrive.java.
{
        if (currentMode == Mode.DEBUG_MODE) {
            debugEnabledMotor++;
            debugEnabledMotor %= 4;
            System.out.println("Current Motor: " + debugEnabledMotor);
        }
    }
Referenced by frc.robot.Robot.checkForButtonPresses().
drive()
void frc.robot.subsystems.MecaDrive.drive (double speedX, double speedY, double rotateSpeed)
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 70 of file MecaDrive.java.
{
        speedX *= speedMultiplier;
        speedY *= speedMultiplier;
        rotateSpeed *= speedMultiplier;
        // these speeds are linearized from 1 to -1
        switch (currentMode){
            case STOP_MODE:
                // STOP!!!!! set motors to 0
                // slower stop
                speedX = slowDown(speedX);
                speedY = slowDown(speedY);
                rotateSpeed = slowDown(rotateSpeed);
                break;
            // TODO: figure out how to implement a debug mode
            // case DEBUG_MODE:
            //  // Debug mode (toggle wheels with left stick button)
            //  switch (debugEnabledMotor){
            //      case 0:
            //          frontLeftMotor.set(ControlMode.PercentOutput, combinedSpeeds[0]);
            //          break;
            //      case 1:
            //          frontRightMotor.set(ControlMode.PercentOutput, combinedSpeeds[1]);
            //          break;
            //      case 2:
            //          rearLeftMotor.set(ControlMode.PercentOutput, combinedSpeeds[2]);
            //          break;
            //      case 3:
            //          rearRightMotor.set(ControlMode.PercentOutput, combinedSpeeds[3]);
            //          break;
            //  }
            //  break;
            case PID_TUNING_MODE:
                // nothing yet
                break;
            default:
                break;
        }
        // method defines Y as left/right and X as forward/backward - contrary to docs, right and forward are positive
        // https://docs.wpilib.org/en/stable/docs/software/pathplanning/trajectory-tutorial/creating-drive-subsystem.html
        mDrive.driveCartesian(speedY, speedX, rotateSpeed);
    }
References frc.robot.subsystems.MecaDrive.slowDown().
Referenced by frc.robot.subsystems.Autonomous.applyChassisSpeeds(), and frc.robot.Robot.drive().
getOdomHeading()
double frc.robot.subsystems.MecaDrive.getOdomHeading ()
Definition at line 264 of file MecaDrive.java.
{
        return mOdom.getPoseMeters().getRotation().getDegrees();
    }
Referenced by frc.robot.subsystems.BetterShuffleboard.pushOdom().
getOdomX()
double frc.robot.subsystems.MecaDrive.getOdomX ()
Definition at line 256 of file MecaDrive.java.
{
        return mOdom.getPoseMeters().getTranslation().getX();
    }
Referenced by frc.robot.subsystems.BetterShuffleboard.pushOdom().
getOdomY()
double frc.robot.subsystems.MecaDrive.getOdomY ()
Definition at line 260 of file MecaDrive.java.
{
        return mOdom.getPoseMeters().getTranslation().getY();
    }
Referenced by frc.robot.subsystems.BetterShuffleboard.pushOdom().
getPose()
Pose2d frc.robot.subsystems.MecaDrive.getPose ()
Returns the currently-estimated pose of the robot.
Returns
The pose.
Definition at line 252 of file MecaDrive.java.
{
        return mOdom.getPoseMeters();
    }
Referenced by frc.robot.subsystems.Autonomous.getChassisSpeeds(), and frc.robot.subsystems.Autonomous.updateTrajectory().
periodic()
void frc.robot.subsystems.MecaDrive.periodic ()
Definition at line 184 of file MecaDrive.java.
{
        // Update the odometry in the periodic block
    }
printActiveMotorDebugMode()
void frc.robot.subsystems.MecaDrive.printActiveMotorDebugMode ()
prints the number of the currently activated motors during debug mode
Definition at line 175 of file MecaDrive.java.
{
        if (currentMode == Mode.DEBUG_MODE) {
            System.out.println("Current Motor: " + debugEnabledMotor);
        }
    }
Referenced by frc.robot.Robot.checkForButtonPresses().
printControlsOfCurrentMode()
void frc.robot.subsystems.MecaDrive.printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 136 of file MecaDrive.java.
{
        System.out.println("Controls:");
        switch(currentMode) {
            case DEFAULT_MODE:
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case DEBUG_MODE:
                System.out.println("A: Cycle active motor");
                System.out.println("B: Print current active motor");
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case STOP_MODE:
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case PID_TUNING_MODE:
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
        }
    }
resetOdometry()
void frc.robot.subsystems.MecaDrive.resetOdometry (Pose2d pose)
Resets the odometry to the specified pose.
Parameters
pose The pose to which to set the odometry.
Definition at line 277 of file MecaDrive.java.
{
        //resetEncoders();
        mOdom.resetPosition(
            new Rotation2d(Math.toRadians(imu.getAngle())), getWheelPositions(), pose);
    }
slowDown()
double frc.robot.subsystems.MecaDrive.slowDown (double inputVelocity) private
This will return a value lower than the input, and it is used to slow down the motors during stop mode.
Parameters
inputVelocity between -1 and 1 (double)
Returns
the new value (lower)
Definition at line 124 of file MecaDrive.java.
{
        // velocity needs to be reduced
        double newVelocity = inputVelocity / Constants.SLOW_DOWN_FACTOR;
        // input has reached cutoff, now returning 0 speed
        if (Math.abs(inputVelocity) < Constants.SLOW_DOWN_CUTOFF){
            newVelocity = 0;
        }
        return newVelocity;
    }
References frc.robot.Constants.SLOW_DOWN_CUTOFF, and frc.robot.Constants.SLOW_DOWN_FACTOR.
Referenced by frc.robot.subsystems.MecaDrive.drive().
updateOdometry()
void frc.robot.subsystems.MecaDrive.updateOdometry ()
Definition at line 188 of file MecaDrive.java.
{
        mOdom.update(new Rotation2d(Math.toRadians(imu.getHeading())), getWheelPositions());
    }
References frc.robot.subsystems.IMU.getHeading().
Referenced by frc.robot.Robot.robotPeriodic().
The documentation for this class was generated from the following file:
MecaDrive.java