2023 Drive base: frc.robot.subsystems.ZED Class Reference
frc.robot.subsystems.ZED Class Reference
Public Member Functions
double getAprilTagX ()
double getAprilTagY ()
double getAprilTagZ ()
Private Attributes
double x
double y
double z
Detailed Description
Definition at line 6 of file ZED.java.
Member Function Documentation
getAprilTagX()
double frc.robot.subsystems.ZED.getAprilTagX ()
Definition at line 11 of file ZED.java.
{
        x = tags.getEntry("x").getDouble(0);
        return x;
    }
References frc.robot.subsystems.ZED.x.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushZED().
getAprilTagY()
double frc.robot.subsystems.ZED.getAprilTagY ()
Definition at line 16 of file ZED.java.
{
        y = tags.getEntry("y").getDouble(0);
        return y;
    }
References frc.robot.subsystems.ZED.y.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushZED().
getAprilTagZ()
double frc.robot.subsystems.ZED.getAprilTagZ ()
Definition at line 21 of file ZED.java.
{
        z = tags.getEntry("z").getDouble(0);
        return z;
    }
References frc.robot.subsystems.ZED.z.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushZED().
Member Data Documentation
x
double frc.robot.subsystems.ZED.x private
Definition at line 8 of file ZED.java.
Referenced by frc.robot.subsystems.ZED.getAprilTagX().
y
double frc.robot.subsystems.ZED.y private
Definition at line 8 of file ZED.java.
Referenced by frc.robot.subsystems.ZED.getAprilTagY().
z
double frc.robot.subsystems.ZED.z private
Definition at line 8 of file ZED.java.
Referenced by frc.robot.subsystems.ZED.getAprilTagZ().
The documentation for this class was generated from the following file:
ZED.java