2023 Drive base: frc.robot.subsystems.TankDrive Class Reference
frc.robot.subsystems.TankDrive Class Reference
Manages the tank drive base.
Public Member Functions
TankDrive (int leftTalonPort, int leftVictorPort, int rightTalonPort, int rightVictorPort)
Constructor for TankDrive Class.
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot tank base from controller input.
void turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
void updateRobotVelocity ()
void getPosition ()
void updatePosition ()
void printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
void AButtonPressed ()
void BButtonPressed ()
void XButtonPressed ()
void YButtonPressed ()
void leftBumperPressed ()
void rightBumperPressed ()
void printActiveMotorDebugMode ()
void cycleMotor ()
Needs to be implemented in sub classes becuase there might be different numbers of motors.
void incrementPIDConstant ()
PID Tuning Mode: Increments the selected PID constant.
void cyclePIDConstant ()
PID Tuning Mode: Cycles between the PID constants.
void toggleDecreasingPIDIncrement ()
void printPIDConstants ()
void resetPosition ()
void printPosition ()
Public Member Functions inherited from frc.robot.subsystems.DriveBase
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot with controller input.
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX)
abstract void printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
void increaseSpeedBracket ()
The speed bracket controls the multiplier for al the speeds So when you change it, lets say, to 1/2 speed, all movement will be at 1/2 speed.
void decreaseSpeedBracket ()
void turnOnDefaultMode ()
void turnOnDebugMode ()
void turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
void turnONPIDTuningMode ()
abstract void cycleMotor ()
Needs to be implemented in sub classes becuase there might be different numbers of motors.
void AButtonPressed ()
void BButtonPressed ()
void XButtonPressed ()
void YButtonPressed ()
void leftBumperPressed ()
void rightBumperPressed ()
Mode getCurrentMode ()
void setCurrentMode (Mode currentMode)
int getDebugEnabledMotor ()
void setDebugEnabledMotor (int debugEnabledMotor)
Trajectory getCurrentTrajectory ()
void setCurrentTrajectory (Trajectory currentTrajectory)
TrajectoryConfig getTrajectoryConfig ()
RamseteController getChassisController ()
double getCurrentTrajectoryTime ()
void resetCurrentTrajectoryTime ()
void incrementCurrentTrajectoryTime ()
Private Member Functions
double slowDown (double inputVelocity)
This will return a value lower than the input, and it is used to slow down the motors during stop mode.
Additional Inherited Members
Protected Attributes inherited from frc.robot.subsystems.DriveBase
TrajectoryConfig trajectoryConfig
Detailed Description
Manages the tank drive base.
Definition at line 27 of file TankDrive.java.
Constructor & Destructor Documentation
TankDrive()
frc.robot.subsystems.TankDrive.TankDrive (int leftTalonPort, int leftVictorPort, int rightTalonPort, int rightVictorPort)
Constructor for TankDrive Class.
Parameters
leftMotorPort
rightMotorPort
Definition at line 79 of file TankDrive.java.
{
        leftVictor = new VictorSPX(leftVictorPort);
        leftSparkMax = new CANSparkMax(leftTalonPort, CANSparkMaxLowLevel.MotorType.kBrushed);
        rightTalon = new TalonSRX(rightTalonPort);
        rightVictor = new VictorSPX(rightVictorPort);
        sparkMaxEncoder = leftSparkMax.getEncoder(SparkMaxRelativeEncoder.Type.kQuadrature, Constants.ENCODER_CPR);
        currentMode = Mode.DEFAULT_MODE;
        leftPID = new PIDController(PIDConstants[0], PIDConstants[1], PIDConstants[2]);
        rightPID = new PIDController(PIDConstants[0], PIDConstants[1], PIDConstants[2]);
        navx = new AHRS(SPI.Port.kMXP);
        //odometer = new DifferentialDriveOdometry(new Rotation2d());
        resetPosition();
        // see declaration in DriveBase
        /*
        This trajecotry config needs a look over, because it has not been tested or planned for tank drive. TankDrive functions should fail if used in autonomous
        trajectoryConfig = new TrajectoryConfig(Constants.maxVelocityMetersPerSecond, Constants.maxAccelerationMetersPerSecond);
        trajectoryConfig.setReversed(true);
        */
    }
References frc.robot.Constants.ENCODER_CPR, and frc.robot.subsystems.TankDrive.resetPosition().
Member Function Documentation
AButtonPressed()
void frc.robot.subsystems.TankDrive.AButtonPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 331 of file TankDrive.java.
{
        switch(currentMode) {
            case DEFAULT_MODE:
                printPosition();
                break;
            case DEBUG_MODE:
                cycleMotor();
                break;
            case PID_TUNING_MODE:
                incrementPIDConstant();
                break;
            default:
                break;
        }
    }
References frc.robot.subsystems.TankDrive.cycleMotor(), frc.robot.subsystems.TankDrive.incrementPIDConstant(), and frc.robot.subsystems.TankDrive.printPosition().
BButtonPressed()
void frc.robot.subsystems.TankDrive.BButtonPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 348 of file TankDrive.java.
{
        switch(currentMode) {
            case DEFAULT_MODE:
                resetPosition();
                break;
            case DEBUG_MODE:
                printActiveMotorDebugMode();
                break;
            case PID_TUNING_MODE:
                cyclePIDConstant();
                break;
            default:
                break;
        }
    }
References frc.robot.subsystems.TankDrive.cyclePIDConstant(), frc.robot.subsystems.TankDrive.printActiveMotorDebugMode(), and frc.robot.subsystems.TankDrive.resetPosition().
cycleMotor()
void frc.robot.subsystems.TankDrive.cycleMotor ()
Needs to be implemented in sub classes becuase there might be different numbers of motors.
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 401 of file TankDrive.java.
{
        debugEnabledMotor++;
        debugEnabledMotor %= 4;
        System.out.println("Current Motor: " + debugEnabledMotor);
    }
Referenced by frc.robot.subsystems.TankDrive.AButtonPressed().
cyclePIDConstant()
void frc.robot.subsystems.TankDrive.cyclePIDConstant ()
PID Tuning Mode: Cycles between the PID constants.
Definition at line 440 of file TankDrive.java.
{
        currentPIDConstant++;
        currentPIDConstant %= 3;
        if(currentPIDConstant == 0) {
            System.out.println("kP Selected");
        }
        else if(currentPIDConstant == 1) {
            System.out.println("kI Selected");
        }
        else if(currentPIDConstant == 2) {
            System.out.println("kD Selected");
        }
    }
Referenced by frc.robot.subsystems.TankDrive.BButtonPressed().
drive()
void frc.robot.subsystems.TankDrive.drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot tank base from controller input.
These are doubles on the interval [-1,1], and come from the controller's analog sticks (circle spinny things)
Parameters
leftAnalogX
leftAnalogY
rightAnalogX
rightAnalogY
we only care about left Y and right X left Y is average velocity right X is velocity difference between wheels
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 115 of file TankDrive.java.
{
        /**
         * we only care about left Y and right X
         * left Y is average velocity
         * right X is velocity difference between wheels
        */
        double x = rightAnalogX;
        double y = leftAnalogY;
        if(Math.abs(x) < Constants.ANALOG_DEAD_ZONE && Math.abs(y) < Constants.ANALOG_DEAD_ZONE) return; // deadzone
        // make sure that both velocities are in [-1, 1]
        double preScaledLeftVel = y - x * rotationalSpeedMultiplier;
        double preScaledRightVel = y + x * rotationalSpeedMultiplier;
        double scaleFactor = 1 / Math.max(Math.max(Math.abs(preScaledLeftVel), Math.abs(preScaledRightVel)), 1);
        // scale to what the controller asks
        leftVel = preScaledLeftVel * scaleFactor * speedMultiplier;
        rightVel = preScaledRightVel * scaleFactor * speedMultiplier;
        // // leftTalon.set(ControlMode.PercentOutput, leftVel);
        // leftVictor.set(ControlMode.PercentOutput, leftVel);
        // leftSparkMax.set(leftVel);
        // rightTalon.set(ControlMode.PercentOutput, rightVel);
        // rightVictor.set(ControlMode.PercentOutput, rightVel);
        // set the motor speeds
        if(currentMode == Mode.DEFAULT_MODE || currentMode == Mode.PID_TUNING_MODE) {
            leftVictor.set(ControlMode.PercentOutput, -1 *leftVel);
            leftSparkMax.set(leftVel);
            rightTalon.set(ControlMode.PercentOutput, rightVel);
            rightVictor.set(ControlMode.PercentOutput, rightVel);
            // PID stuff
            // actual angular velocities converted to radians per second
            double leftAngVel = sparkMaxEncoder.getVelocity() * Constants.SPARK_MAX_CONVERSION_FACTOR;
            double rightAngVel = rightTalon.getSelectedSensorVelocity() * Constants.TALON_CONVERSION_FACTOR;
            // normalized (actual) angular velocities
            double normalLeftAngVel = leftAngVel / maxAngularVel;
            double normalRightAngVel = rightAngVel / maxAngularVel;
            // set the motors according to the PID
            double leftPIDValue = leftPID.calculate(normalLeftAngVel, leftVel);
            double rightPIDValue = rightPID.calculate(normalRightAngVel, rightVel);
            leftVictor.set(ControlMode.PercentOutput, -1 * leftPIDValue);
            leftSparkMax.set(leftPIDValue);
            // System.out.println("Analog: " + leftAnalogY + ", Input: " + rightVel + ", Measured: " + rightAngVel + ", Normalized: " + normalRightAngVel + ", PID: " + rightPIDValue);
            System.out.println("Right: " + normalRightAngVel + ", Left: " + normalLeftAngVel);
            rightTalon.set(ControlMode.PercentOutput, rightPIDValue);
            rightVictor.set(ControlMode.PercentOutput, rightPIDValue);
        } else if (currentMode == Mode.DEBUG_MODE) {
            switch (debugEnabledMotor){
                case 0:
                    leftVictor.set(ControlMode.PercentOutput, -1 * leftVel);
                    break;
                case 1:
                    rightVictor.set(ControlMode.PercentOutput, rightVel);
                    break;
                case 2:
                    rightTalon.set(ControlMode.PercentOutput, rightVel);
                    break;
                case 3:
                    leftSparkMax.set(leftVel);
                    break;
            }
        } else if (currentMode == Mode.STOP_MODE){
            // STOP!!!!! set motors to 0
            // slower stop
            slowingLeftVel = slowDown(slowingLeftVel);
            slowingRightVel = slowDown(slowingRightVel);
            leftVictor.set(ControlMode.PercentOutput, -1 *slowingLeftVel);
            leftSparkMax.set(slowingLeftVel);
            rightTalon.set(ControlMode.PercentOutput, slowingRightVel);
            rightVictor.set(ControlMode.PercentOutput, slowingRightVel);
        }
        updatePosition();
        // System.out.println(rightTalon.getSelectedSensorVelocity()); // clicks per 100ms
        // System.out.println(rightTalon.getSelectedSensorVelocity() * 10 * 60 / 4096);
        // System.out.println(sparkMaxEncoder.getVelocity()); // actual rpm
        // System.out.println("");
        // // Print angular velocity and motor use level
        // // get rotational speeds from the motors on each side
        // // divide by 60 to get rotations per second
        // double leftRPS = -1 * sparkMaxEncoder.getVelocity() / 60;
        // if (Math.abs(leftRPS) > 0.1){
        //  // // multiply by 10 because this is per 100ms - we want rps
        //  double rightRPS = rightTalon.getSelectedSensorVelocity() * 10 / Constants.ENCODER_CPR;
        //  System.out.println("Right Rps: " + rightRPS + "\nLeft RPS: " + leftRPS);
        //  System.out.println("Right velocity from controller: " + rightVel + "\nLeft Velocity from controller: " + leftVel);
        // }
    }
References frc.robot.Constants.ANALOG_DEAD_ZONE, frc.robot.subsystems.TankDrive.slowDown(), frc.robot.Constants.SPARK_MAX_CONVERSION_FACTOR, frc.robot.Constants.TALON_CONVERSION_FACTOR, and frc.robot.subsystems.TankDrive.updatePosition().
getPosition()
void frc.robot.subsystems.TankDrive.getPosition ()
Definition at line 280 of file TankDrive.java.
    {
    }
incrementPIDConstant()
void frc.robot.subsystems.TankDrive.incrementPIDConstant ()
PID Tuning Mode: Increments the selected PID constant.
Definition at line 411 of file TankDrive.java.
{
        if(increasingPIDConstant) {
            PIDConstants[currentPIDConstant] += PIDIncrements[currentPIDConstant];
        } else {
            PIDConstants[currentPIDConstant] -= PIDIncrements[currentPIDConstant];
        }
        // make sure constants are in [0, constantMax]
        PIDConstants[currentPIDConstant] = Math.min(PIDConstants[currentPIDConstant], PIDMaximums[currentPIDConstant]);
        PIDConstants[currentPIDConstant] = Math.max(PIDConstants[currentPIDConstant], 0);
        // print PID constants
        System.out.println("kP: " + PIDConstants[0] + ", kI: " + PIDConstants[1] + ", kD: " + PIDConstants[2]);
        // set PID constant in the PID controllers
        if(currentPIDConstant == 0) {
            leftPID.setP(PIDConstants[0]);
            rightPID.setP(PIDConstants[0]);
        } else if (currentPIDConstant == 1) {
            leftPID.setI(PIDConstants[1]);
            rightPID.setI(PIDConstants[1]);
        } else if (currentPIDConstant == 2) {
            leftPID.setD(PIDConstants[2]);
            rightPID.setD(PIDConstants[2]);
        }
    }
Referenced by frc.robot.subsystems.TankDrive.AButtonPressed().
leftBumperPressed()
void frc.robot.subsystems.TankDrive.leftBumperPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 387 of file TankDrive.java.
{
        decreaseSpeedBracket();
    }
References frc.robot.subsystems.DriveBase.decreaseSpeedBracket().
printActiveMotorDebugMode()
void frc.robot.subsystems.TankDrive.printActiveMotorDebugMode ()
Definition at line 397 of file TankDrive.java.
{
        System.out.println("Current Motor: " + debugEnabledMotor);
    }
Referenced by frc.robot.subsystems.TankDrive.BButtonPressed().
printControlsOfCurrentMode()
void frc.robot.subsystems.TankDrive.printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 300 of file TankDrive.java.
{
        System.out.println("Controls:");
        switch(currentMode) {
            case DEFAULT_MODE:
                System.out.println("A: Print position");
                System.out.println("B: Reset position to 0");
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case DEBUG_MODE:
                System.out.println("A: Cycle active motor");
                System.out.println("B: Print current active motor");
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case STOP_MODE:
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
            case PID_TUNING_MODE:
                System.out.println("A: Increment selected PID constant");
                System.out.println("B: Cycle selected PID constant");
                System.out.println("X: Toggle between increasing/decreasing PID constant");
                System.out.println("Y: Print PID constant");
                System.out.println("Left Bracket: Decrease speed multiplier");
                System.out.println("Right Bracket: Increase speed multiplier");
                break;
        }
    }
printPIDConstants()
void frc.robot.subsystems.TankDrive.printPIDConstants ()
Definition at line 467 of file TankDrive.java.
{
        System.out.println("kP: " + PIDConstants[0] + ", kI: " + PIDConstants[1] + ", kD: " + PIDConstants[2]);
    }
Referenced by frc.robot.subsystems.TankDrive.YButtonPressed().
printPosition()
void frc.robot.subsystems.TankDrive.printPosition ()
Definition at line 481 of file TankDrive.java.
    {
        Pose2d posFromWheelDisplacement = odometer.getPoseMeters();
        System.out.println("Position from odometer and wheel: ");
        System.out.println("X: " + posFromWheelDisplacement.getX() + " Y: " + posFromWheelDisplacement.getY() + " rotation: " + posFromWheelDisplacement.getRotation());
        System.out.println("\nPosition info from navx: ");
        System.out.println("X: " + navx.getDisplacementX() + " Y: " + navx.getDisplacementY() + " rotation: " + navx.getAngle());
        System.out.println();
        // get the linear position of the left wheel and convert to meters
        double leftWheelPos = -1 * sparkMaxEncoder.getPosition() * 2 * Math.PI * Constants.TANK_WHEEL_RADIUS;
        // get the linear position of the right wheel and convert to meters
        double rightWheelPos = rightTalon.getSelectedSensorPosition() / Constants.ENCODER_CPR * 2 * Math.PI * Constants.TANK_WHEEL_RADIUS;
        System.out.println("Right Pos: " + rightWheelPos + " left pos: " + leftWheelPos);
        // Print angular velocity and motor use level
        // get rotational speeds from the motors on each side
        // divide by 60 to get rotations per second
        double leftRPS = -1 * sparkMaxEncoder.getVelocity() / 60;
        // // multiply by 10 because this is per 100ms - we want rps
        double rightRPS = rightTalon.getSelectedSensorVelocity() * 10 / Constants.ENCODER_CPR;
        System.out.println("Right Rps: " + rightRPS + "\nLeft RPS: " + leftRPS);
    }
References frc.robot.Constants.ENCODER_CPR, and frc.robot.Constants.TANK_WHEEL_RADIUS.
Referenced by frc.robot.subsystems.TankDrive.AButtonPressed().
resetPosition()
void frc.robot.subsystems.TankDrive.resetPosition ()
Definition at line 471 of file TankDrive.java.
    {
        // reset the sensors to zero the position
        navx.reset();
        navx.resetDisplacement();
        sparkMaxEncoder.setPosition(0);
        rightTalon.setSelectedSensorPosition(0);
    //  odometer.resetPosition(new Pose2d(), new Rotation2d());
    }
Referenced by frc.robot.subsystems.TankDrive.BButtonPressed(), and frc.robot.subsystems.TankDrive.TankDrive().
rightBumperPressed()
void frc.robot.subsystems.TankDrive.rightBumperPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 392 of file TankDrive.java.
{
        increaseSpeedBracket();
    }
References frc.robot.subsystems.DriveBase.increaseSpeedBracket().
slowDown()
double frc.robot.subsystems.TankDrive.slowDown (double inputVelocity) private
This will return a value lower than the input, and it is used to slow down the motors during stop mode.
Parameters
inputVelocity between -1 and 1 (double)
Returns
the new value (lower)
Definition at line 240 of file TankDrive.java.
{
        // input is between -1 and 1
        double newVelocity;
        if (Math.abs(inputVelocity) > Constants.SLOW_DOWN_CUTOFF){
            // velocity still needs to be reduced (magnatude is above cutoff)
            newVelocity = inputVelocity / Constants.SLOW_DOWN_FACTOR;
        } else {
            // input has reached cutoff, now returning 0 speed
            return 0;
        }
        return newVelocity;
    }
References frc.robot.Constants.SLOW_DOWN_CUTOFF, and frc.robot.Constants.SLOW_DOWN_FACTOR.
Referenced by frc.robot.subsystems.TankDrive.drive().
toggleDecreasingPIDIncrement()
void frc.robot.subsystems.TankDrive.toggleDecreasingPIDIncrement ()
Definition at line 457 of file TankDrive.java.
{
        if(increasingPIDConstant) {
            increasingPIDConstant = false;
            System.out.println("Decreasing PID Constants");
        } else {
            increasingPIDConstant = true;
            System.out.println("Increasing PID Constants");
        }
    }
Referenced by frc.robot.subsystems.TankDrive.XButtonPressed().
turnOnStopMode()
void frc.robot.subsystems.TankDrive.turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 254 of file TankDrive.java.
{
        if(currentMode == Mode.STOP_MODE) return;
        currentMode = Mode.STOP_MODE;
        // Stop mode activated, so now the robot needs to slow down
        // start by saving the last left and right velocities
        slowingLeftVel = leftVel;
        slowingRightVel = rightVel;
        System.out.println("STOP MODE");
    }
updatePosition()
void frc.robot.subsystems.TankDrive.updatePosition ()
Definition at line 285 of file TankDrive.java.
    {
        // get the linear position of the left wheel and convert to meters
        double leftWheelPos = -1 * sparkMaxEncoder.getPosition() * 2 * Math.PI * Constants.TANK_WHEEL_RADIUS;
        // get the linear position of the right wheel and convert to meters
        double rightWheelPos = rightTalon.getSelectedSensorPosition() / Constants.ENCODER_CPR * 2 * Math.PI * Constants.TANK_WHEEL_RADIUS;
        // get the angle of the robot
        double theta = navx.getAngle() / 180 * Math.PI;
        Rotation2d rot = new Rotation2d(theta);
        odometer.update(rot, leftWheelPos, rightWheelPos);
    }
References frc.robot.Constants.TANK_WHEEL_RADIUS.
Referenced by frc.robot.subsystems.TankDrive.drive().
updateRobotVelocity()
void frc.robot.subsystems.TankDrive.updateRobotVelocity ()
Definition at line 264 of file TankDrive.java.
{
        // get rotational speeds from the motors on each side
        // divide by 60 to get rotations per second
        // double leftRPS = -1 * sparkMaxEncoder.getVelocity() / 60;
        // // multiply by 10 because this is per 100ms - we want rps
        // double rightRPS = rightTalon.getSelectedSensorVelocity() * 10 / Constants.ENCODER_CPR;
        // // find linear velocities in m/s
        // double leftVel = (leftRPS * 2 * Math.PI) * Constants.TANK_WHEEL_RADIUS;
        // double rightVel = (rightRPS * 2 * Math.PI) * Constants.TANK_WHEEL_RADIUS;
        // currentSpeeds.leftMetersPerSecond = leftVel;
        // currentSpeeds.rightMetersPerSecond = rightVel;
    }
XButtonPressed()
void frc.robot.subsystems.TankDrive.XButtonPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 365 of file TankDrive.java.
{
        switch(currentMode) {
            case PID_TUNING_MODE:
                toggleDecreasingPIDIncrement();
                break;
            default:
                break;
        }
    }
References frc.robot.subsystems.TankDrive.toggleDecreasingPIDIncrement().
YButtonPressed()
void frc.robot.subsystems.TankDrive.YButtonPressed ()
Reimplemented from frc.robot.subsystems.DriveBase.
Definition at line 376 of file TankDrive.java.
{
        switch(currentMode) {
            case PID_TUNING_MODE:
                printPIDConstants();
                break;
            default:
                break;
        }
    }
References frc.robot.subsystems.TankDrive.printPIDConstants().
The documentation for this class was generated from the following file:
TankDrive.java