2023 Drive base: frc.robot.subsystems.Limelight Class Reference
frc.robot.subsystems.Limelight Class Reference
Public Member Functions
double getX ()
double getY ()
double getArea ()
Private Attributes
double x
double y
double area
Detailed Description
Definition at line 8 of file Limelight.java.
Member Function Documentation
getArea()
double frc.robot.subsystems.Limelight.getArea ()
Definition at line 24 of file Limelight.java.
{
        area = table.getEntry("ta").getDouble(0);
        return area;
    }
References frc.robot.subsystems.Limelight.area.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushLimelight().
getX()
double frc.robot.subsystems.Limelight.getX ()
Definition at line 14 of file Limelight.java.
{
        x = table.getEntry("tx").getDouble(0);
        return x;
    }
References frc.robot.subsystems.Limelight.x.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushLimelight().
getY()
double frc.robot.subsystems.Limelight.getY ()
Definition at line 19 of file Limelight.java.
{
        y = table.getEntry("ty").getDouble(0);
        return y;
    }
References frc.robot.subsystems.Limelight.y.
Referenced by frc.robot.subsystems.BetterShuffleboard.pushLimelight().
Member Data Documentation
area
double frc.robot.subsystems.Limelight.area private
Definition at line 10 of file Limelight.java.
Referenced by frc.robot.subsystems.Limelight.getArea().
x
double frc.robot.subsystems.Limelight.x private
Definition at line 10 of file Limelight.java.
Referenced by frc.robot.subsystems.Limelight.getX().
y
double frc.robot.subsystems.Limelight.y private
Definition at line 10 of file Limelight.java.
Referenced by frc.robot.subsystems.Limelight.getY().
The documentation for this class was generated from the following file:
Limelight.java