2023 Drive base: frc.robot.subsystems.BetterShuffleboard Class Reference
frc.robot.subsystems.BetterShuffleboard Class Reference
Public Member Functions
BetterShuffleboard ()
void pushDashboard (Limelight limelight, IMU imu, MecaDrive drive, ZED zed)
void updateControllerExponents ()
void pushOdom (MecaDrive drive)
void pushLimelight (Limelight limelight)
void pushIMU (IMU imu)
void pushZED (ZED zed)
Detailed Description
Definition at line 12 of file BetterShuffleboard.java.
Constructor & Destructor Documentation
BetterShuffleboard()
frc.robot.subsystems.BetterShuffleboard.BetterShuffleboard ()
Definition at line 25 of file BetterShuffleboard.java.
{
        tuningTab = Shuffleboard.getTab("Tuning");
        // create widgets for tuning tab
        leftXExp = tuningTab.add("LeftXExp", Constants.LEFT_X_EXPONENT)
            .withWidget(BuiltInWidgets.kNumberSlider)
            .withProperties(Map.of("min", 1, "max", 5))
            .getEntry();
        leftXExp.setDouble(Constants.LEFT_X_EXPONENT);
        leftYExp = tuningTab.add("LeftYExp", Constants.LEFT_Y_EXPONENT)
            .withWidget(BuiltInWidgets.kNumberSlider)
            .withProperties(Map.of("min", 1, "max", 5))
            .getEntry();
        leftYExp.setDouble(Constants.LEFT_Y_EXPONENT);
        rightXExp = tuningTab.add("RightXExp", Constants.RIGHT_X_EXPONENT)
            .withWidget(BuiltInWidgets.kNumberSlider)
            .withProperties(Map.of("min", 1, "max", 5))
            .getEntry();
        rightXExp.setDouble(Constants.RIGHT_X_EXPONENT);
        rightYExp = tuningTab.add("RightYExp", Constants.RIGHT_Y_EXPONENT)
            .withWidget(BuiltInWidgets.kNumberSlider)
            .withProperties(Map.of("min", 1, "max", 5))
            .getEntry();
        rightYExp.setDouble(Constants.RIGHT_Y_EXPONENT);
        debugTab = Shuffleboard.getTab("Debug");
        odomTab = Shuffleboard.getTab("Odometry");
        odomX = odomTab.add("OdomX", 0)
            .withWidget(BuiltInWidgets.kGraph)
            .withProperties(Map.of("visible time", 20))
            .getEntry();
        odomY = odomTab.add("OdomY", 0)
            .withWidget(BuiltInWidgets.kGraph)
            .withProperties(Map.of("visible time", 20))
            .getEntry();
        odomHead = odomTab.add("OdomHead", 0)
            .withWidget(BuiltInWidgets.kDial)
            .withProperties(Map.of("min", -180, "max", 180))
            .getEntry();
        FRVel = odomTab.add("FRVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        FLVel = odomTab.add("FLVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        RRVel = odomTab.add("RRVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        RLVel = odomTab.add("RLVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavXVel = odomTab.add("NavXVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavYVel = odomTab.add("NavYVel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavRotationRateZ = odomTab.add("NavRotationRateZ", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavXAccel = odomTab.add("NavXAccel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavYAccel = odomTab.add("NavYAccel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavZAccel = odomTab.add("NavZAccel", 0)
            .withWidget(BuiltInWidgets.kNumberBar)
            .withProperties(Map.of("min", -5, "max", 5))
            .getEntry();
        NavRoll = odomTab.add("NavRoll", 0)
            .withWidget(BuiltInWidgets.kDial)
            .withProperties(Map.of("min", -180, "max", 180))
            .getEntry();
        NavPitch = odomTab.add("NavPitch", 0)
            .withWidget(BuiltInWidgets.kDial)
            .withProperties(Map.of("min", -180, "max", 180))
            .getEntry();
        NavHeading = odomTab.add("NavHeading", 0)
            .withWidget(BuiltInWidgets.kDial)
            .withProperties(Map.of("min", -180, "max", 180))
            .getEntry();
        NavConnected = odomTab.add("NavConnected", 0)
            .withWidget(BuiltInWidgets.kBooleanBox)
            .getEntry();
    }
References frc.robot.Constants.LEFT_X_EXPONENT, frc.robot.Constants.LEFT_Y_EXPONENT, frc.robot.Constants.RIGHT_X_EXPONENT, and frc.robot.Constants.RIGHT_Y_EXPONENT.
Member Function Documentation
pushDashboard()
void frc.robot.subsystems.BetterShuffleboard.pushDashboard (Limelight limelight, IMU imu, MecaDrive drive, ZED zed)
Definition at line 120 of file BetterShuffleboard.java.
{
        pushLimelight(limelight);
        pushIMU(imu);
        pushZED(zed);
        pushOdom(drive);
    }
References frc.robot.subsystems.BetterShuffleboard.pushIMU(), frc.robot.subsystems.BetterShuffleboard.pushLimelight(), frc.robot.subsystems.BetterShuffleboard.pushOdom(), and frc.robot.subsystems.BetterShuffleboard.pushZED().
Referenced by frc.robot.Robot.robotPeriodic().
pushIMU()
void frc.robot.subsystems.BetterShuffleboard.pushIMU (IMU imu)
Definition at line 150 of file BetterShuffleboard.java.
{
        // SmartDashboard.putNumber("NavX", imu.getDisplacementX());
        // SmartDashboard.putNumber("NavY", imu.getDisplacementY());
        // SmartDashboard.putNumber("NavZ", imu.getDisplacementZ());
        NavXVel.setDouble(imu.getVelocityX());
        NavYVel.setDouble(imu.getVelocityY());
        NavXAccel.setDouble(imu.getWorldLinearAccelX());
        NavYAccel.setDouble(imu.getWorldLinearAccelY());
        NavZAccel.setDouble(imu.getWorldLinearAccelZ());
        NavRoll.setDouble(imu.getRoll());
        NavPitch.setDouble(imu.getPitch());
        NavHeading.setDouble(imu.getHeading());
        NavRotationRateZ.setDouble(imu.getRate());
        NavConnected.setBoolean(imu.isConnected());
    }
References frc.robot.subsystems.IMU.getHeading().
Referenced by frc.robot.subsystems.BetterShuffleboard.pushDashboard().
pushLimelight()
void frc.robot.subsystems.BetterShuffleboard.pushLimelight (Limelight limelight)
Definition at line 144 of file BetterShuffleboard.java.
{
        SmartDashboard.putNumber("LimelightX", limelight.getX());
        SmartDashboard.putNumber("LimelightY", limelight.getY());
        SmartDashboard.putNumber("LimelightArea", limelight.getArea());
    }
References frc.robot.subsystems.Limelight.getArea(), frc.robot.subsystems.Limelight.getX(), and frc.robot.subsystems.Limelight.getY().
Referenced by frc.robot.subsystems.BetterShuffleboard.pushDashboard().
pushOdom()
void frc.robot.subsystems.BetterShuffleboard.pushOdom (MecaDrive drive)
Definition at line 134 of file BetterShuffleboard.java.
{
        odomX.setDouble(drive.getOdomX());
        odomY.setDouble(drive.getOdomY());
        odomHead.setDouble(drive.getOdomHeading());
        FLVel.setDouble(drive.getWheelSpeeds().frontLeftMetersPerSecond);
        FRVel.setDouble(drive.getWheelSpeeds().frontRightMetersPerSecond);
        RLVel.setDouble(drive.getWheelSpeeds().rearLeftMetersPerSecond);
        RRVel.setDouble(drive.getWheelSpeeds().rearRightMetersPerSecond);
    }
References frc.robot.subsystems.MecaDrive.getOdomHeading(), frc.robot.subsystems.MecaDrive.getOdomX(), and frc.robot.subsystems.MecaDrive.getOdomY().
Referenced by frc.robot.subsystems.BetterShuffleboard.pushDashboard().
pushZED()
void frc.robot.subsystems.BetterShuffleboard.pushZED (ZED zed)
Definition at line 171 of file BetterShuffleboard.java.
{
        SmartDashboard.putNumber("AprilTagX", zed.getAprilTagX());
        SmartDashboard.putNumber("AprilTagY", zed.getAprilTagY());
        SmartDashboard.putNumber("AprilTagZ", zed.getAprilTagZ());
    }
References frc.robot.subsystems.ZED.getAprilTagX(), frc.robot.subsystems.ZED.getAprilTagY(), and frc.robot.subsystems.ZED.getAprilTagZ().
Referenced by frc.robot.subsystems.BetterShuffleboard.pushDashboard().
updateControllerExponents()
void frc.robot.subsystems.BetterShuffleboard.updateControllerExponents ()
Definition at line 127 of file BetterShuffleboard.java.
{
        Constants.LEFT_X_EXPONENT = leftXExp.getDouble(2);
        Constants.LEFT_Y_EXPONENT = leftYExp.getDouble(2);
        Constants.RIGHT_X_EXPONENT = rightXExp.getDouble(2);
        Constants.RIGHT_Y_EXPONENT = rightYExp.getDouble(2);
    }
Referenced by frc.robot.Robot.teleopInit().
The documentation for this class was generated from the following file:
BetterShuffleboard.java