2023 Drive base: frc.robot.subsystems.DriveBase Class Reference
frc.robot.subsystems.DriveBase Class Reference abstract
Classes
enum Mode
Public Member Functions
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot with controller input.
void drive (double leftAnalogX, double leftAnalogY, double rightAnalogX)
abstract void printControlsOfCurrentMode ()
Prints the controls of the current driving mode.
void increaseSpeedBracket ()
The speed bracket controls the multiplier for al the speeds So when you change it, lets say, to 1/2 speed, all movement will be at 1/2 speed.
void decreaseSpeedBracket ()
void turnOnDefaultMode ()
void turnOnDebugMode ()
void turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
void turnONPIDTuningMode ()
abstract void cycleMotor ()
Needs to be implemented in sub classes becuase there might be different numbers of motors.
void AButtonPressed ()
void BButtonPressed ()
void XButtonPressed ()
void YButtonPressed ()
void leftBumperPressed ()
void rightBumperPressed ()
Mode getCurrentMode ()
void setCurrentMode (Mode currentMode)
int getDebugEnabledMotor ()
void setDebugEnabledMotor (int debugEnabledMotor)
Trajectory getCurrentTrajectory ()
void setCurrentTrajectory (Trajectory currentTrajectory)
TrajectoryConfig getTrajectoryConfig ()
RamseteController getChassisController ()
double getCurrentTrajectoryTime ()
void resetCurrentTrajectoryTime ()
void incrementCurrentTrajectoryTime ()
Protected Attributes
TrajectoryConfig trajectoryConfig
Private Attributes
Trajectory currentTrajectory
double currentTrajectoryTime
final RamseteController chassisController = new RamseteController(Constants.RAMSETE_B, Constants.RAMSETE_ZETA)
Detailed Description
Definition at line 10 of file DriveBase.java.
Member Function Documentation
AButtonPressed()
void frc.robot.subsystems.DriveBase.AButtonPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 126 of file DriveBase.java.
{}
BButtonPressed()
void frc.robot.subsystems.DriveBase.BButtonPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 128 of file DriveBase.java.
{}
cycleMotor()
abstract void frc.robot.subsystems.DriveBase.cycleMotor () abstract
Needs to be implemented in sub classes becuase there might be different numbers of motors.
Reimplemented in frc.robot.subsystems.MecaDrive, and frc.robot.subsystems.TankDrive.
decreaseSpeedBracket()
void frc.robot.subsystems.DriveBase.decreaseSpeedBracket ()
Definition at line 72 of file DriveBase.java.
{
        // the min is 0.2 because below that the robot is unlikely to move
        speedMultiplier = Math.max(0.2, speedMultiplier - 0.1);
        System.out.println("Current speed multiplier: " + speedMultiplier);
    }
Referenced by frc.robot.Robot.checkForButtonPresses(), and frc.robot.subsystems.TankDrive.leftBumperPressed().
drive() [1/2]
void frc.robot.subsystems.DriveBase.drive (double leftAnalogX, double leftAnalogY, double rightAnalogX)
Reimplemented in frc.robot.subsystems.MecaDrive.
Definition at line 53 of file DriveBase.java.
                                          {};
drive() [2/2]
void frc.robot.subsystems.DriveBase.drive (double leftAnalogX, double leftAnalogY, double rightAnalogX, double rightAnalogY)
Drive the robot with controller input.
These are doubles on the interval [-1, 1] and come from the controller's analog sticks
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 49 of file DriveBase.java.
                                                               {};
getChassisController()
RamseteController frc.robot.subsystems.DriveBase.getChassisController ()
Definition at line 160 of file DriveBase.java.
{
        return chassisController;
    }
References frc.robot.subsystems.DriveBase.chassisController.
Referenced by frc.robot.subsystems.Autonomous.getChassisSpeeds().
getCurrentMode()
Mode frc.robot.subsystems.DriveBase.getCurrentMode ()
Definition at line 139 of file DriveBase.java.
{
        return currentMode;
    }
getCurrentTrajectory()
Trajectory frc.robot.subsystems.DriveBase.getCurrentTrajectory ()
Definition at line 151 of file DriveBase.java.
{
        return currentTrajectory;
    }
References frc.robot.subsystems.DriveBase.currentTrajectory.
Referenced by frc.robot.subsystems.Autonomous.getChassisSpeeds().
getCurrentTrajectoryTime()
double frc.robot.subsystems.DriveBase.getCurrentTrajectoryTime ()
Definition at line 163 of file DriveBase.java.
{
        return currentTrajectoryTime;
    }
References frc.robot.subsystems.DriveBase.currentTrajectoryTime.
Referenced by frc.robot.subsystems.Autonomous.getChassisSpeeds().
getDebugEnabledMotor()
int frc.robot.subsystems.DriveBase.getDebugEnabledMotor ()
Definition at line 145 of file DriveBase.java.
{
        return debugEnabledMotor;
    }
getTrajectoryConfig()
TrajectoryConfig frc.robot.subsystems.DriveBase.getTrajectoryConfig ()
Definition at line 157 of file DriveBase.java.
{
        return trajectoryConfig;
    }
References frc.robot.subsystems.DriveBase.trajectoryConfig.
Referenced by frc.robot.subsystems.Autonomous.updateTrajectory().
increaseSpeedBracket()
void frc.robot.subsystems.DriveBase.increaseSpeedBracket ()
The speed bracket controls the multiplier for al the speeds So when you change it, lets say, to 1/2 speed, all movement will be at 1/2 speed.
Definition at line 67 of file DriveBase.java.
{
        speedMultiplier = Math.min(1, speedMultiplier + 0.1);
        System.out.println("Current speed multiplier: " + speedMultiplier);
    }
Referenced by frc.robot.Robot.checkForButtonPresses(), and frc.robot.subsystems.TankDrive.rightBumperPressed().
incrementCurrentTrajectoryTime()
void frc.robot.subsystems.DriveBase.incrementCurrentTrajectoryTime ()
Definition at line 169 of file DriveBase.java.
{
        currentTrajectoryTime += Constants.SECONDS_BETWEEN_CODE_PERIODS;
    }
References frc.robot.subsystems.DriveBase.currentTrajectoryTime, and frc.robot.Constants.SECONDS_BETWEEN_CODE_PERIODS.
Referenced by frc.robot.Robot.autonomousPeriodic().
leftBumperPressed()
void frc.robot.subsystems.DriveBase.leftBumperPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 134 of file DriveBase.java.
{}
printControlsOfCurrentMode()
abstract void frc.robot.subsystems.DriveBase.printControlsOfCurrentMode () abstract
Prints the controls of the current driving mode.
Reimplemented in frc.robot.subsystems.MecaDrive, and frc.robot.subsystems.TankDrive.
Referenced by frc.robot.subsystems.DriveBase.turnOnDebugMode(), frc.robot.subsystems.DriveBase.turnOnDefaultMode(), frc.robot.subsystems.DriveBase.turnONPIDTuningMode(), and frc.robot.subsystems.DriveBase.turnOnStopMode().
resetCurrentTrajectoryTime()
void frc.robot.subsystems.DriveBase.resetCurrentTrajectoryTime ()
Definition at line 166 of file DriveBase.java.
{
        currentTrajectoryTime = 0;
    }
References frc.robot.subsystems.DriveBase.currentTrajectoryTime.
Referenced by frc.robot.Robot.autonomousCheckForButtonPresses(), and frc.robot.Robot.autonomousInit().
rightBumperPressed()
void frc.robot.subsystems.DriveBase.rightBumperPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 136 of file DriveBase.java.
{}
setCurrentMode()
void frc.robot.subsystems.DriveBase.setCurrentMode (Mode currentMode)
Definition at line 142 of file DriveBase.java.
{
        this.currentMode = currentMode;
    }
setCurrentTrajectory()
void frc.robot.subsystems.DriveBase.setCurrentTrajectory (Trajectory currentTrajectory)
Definition at line 154 of file DriveBase.java.
{
        this.currentTrajectory = currentTrajectory;
    }
References frc.robot.subsystems.DriveBase.currentTrajectory.
Referenced by frc.robot.subsystems.Autonomous.updateTrajectory().
setDebugEnabledMotor()
void frc.robot.subsystems.DriveBase.setDebugEnabledMotor (int debugEnabledMotor)
Definition at line 148 of file DriveBase.java.
{
        this.debugEnabledMotor = debugEnabledMotor;
    }
turnOnDebugMode()
void frc.robot.subsystems.DriveBase.turnOnDebugMode ()
Definition at line 87 of file DriveBase.java.
{
        if(currentMode == Mode.DEBUG_MODE) return;
        currentMode = Mode.DEBUG_MODE;
        System.out.println("********************************");
        System.out.println("Current Mode: DEBUG Mode");
        System.out.println("********************************");
        printControlsOfCurrentMode();
    }
References frc.robot.subsystems.DriveBase.printControlsOfCurrentMode().
Referenced by frc.robot.Robot.checkForModeSwitches().
turnOnDefaultMode()
void frc.robot.subsystems.DriveBase.turnOnDefaultMode ()
Definition at line 78 of file DriveBase.java.
{
        if(currentMode == Mode.DEFAULT_MODE) return;
        currentMode = Mode.DEFAULT_MODE;
        System.out.println("********************************");
        System.out.println("Current Mode: DEFAULT Mode");
        System.out.println("********************************");
        printControlsOfCurrentMode();
    }
References frc.robot.subsystems.DriveBase.printControlsOfCurrentMode().
Referenced by frc.robot.Robot.checkForModeSwitches().
turnONPIDTuningMode()
void frc.robot.subsystems.DriveBase.turnONPIDTuningMode ()
Definition at line 110 of file DriveBase.java.
{
        if(currentMode == Mode.PID_TUNING_MODE) return;
        currentMode = Mode.PID_TUNING_MODE;
        System.out.println("********************************");
        System.out.println("Current Mode: PID TUNING Mode");
        System.out.println("********************************");
        printControlsOfCurrentMode();
    }
References frc.robot.subsystems.DriveBase.printControlsOfCurrentMode().
Referenced by frc.robot.Robot.checkForModeSwitches().
turnOnStopMode()
void frc.robot.subsystems.DriveBase.turnOnStopMode ()
should be overridden for actual functionality because depends on drive base specifc speeds (for tank drive, there is a left and right speed, whereas for mecanum there are 4)
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 101 of file DriveBase.java.
{
        if(currentMode == Mode.STOP_MODE) return;
        currentMode = Mode.STOP_MODE;
        System.out.println("********************************");
        System.out.println("Current Mode: STOP Mode");
        System.out.println("********************************");
        printControlsOfCurrentMode();
    }
References frc.robot.subsystems.DriveBase.printControlsOfCurrentMode().
Referenced by frc.robot.Robot.checkForModeSwitches().
XButtonPressed()
void frc.robot.subsystems.DriveBase.XButtonPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 130 of file DriveBase.java.
{}
YButtonPressed()
void frc.robot.subsystems.DriveBase.YButtonPressed ()
Reimplemented in frc.robot.subsystems.TankDrive.
Definition at line 132 of file DriveBase.java.
{}
Member Data Documentation
chassisController
final RamseteController frc.robot.subsystems.DriveBase.chassisController = new RamseteController(Constants.RAMSETE_B, Constants.RAMSETE_ZETA) private
Definition at line 39 of file DriveBase.java.
Referenced by frc.robot.subsystems.DriveBase.getChassisController().
currentTrajectory
Trajectory frc.robot.subsystems.DriveBase.currentTrajectory private
Definition at line 30 of file DriveBase.java.
Referenced by frc.robot.subsystems.DriveBase.getCurrentTrajectory(), and frc.robot.subsystems.DriveBase.setCurrentTrajectory().
currentTrajectoryTime
double frc.robot.subsystems.DriveBase.currentTrajectoryTime private
Definition at line 31 of file DriveBase.java.
Referenced by frc.robot.subsystems.DriveBase.getCurrentTrajectoryTime(), frc.robot.subsystems.DriveBase.incrementCurrentTrajectoryTime(), and frc.robot.subsystems.DriveBase.resetCurrentTrajectoryTime().
trajectoryConfig
TrajectoryConfig frc.robot.subsystems.DriveBase.trajectoryConfig protected
Definition at line 35 of file DriveBase.java.
Referenced by frc.robot.subsystems.DriveBase.getTrajectoryConfig(), and frc.robot.subsystems.MecaDrive.MecaDrive().
The documentation for this class was generated from the following file:
DriveBase.java